### STAGE 2: Run ###
FROM nginxinc/nginx-unprivileged

#### copy nginx conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

#### copy artifact build from the 'build environment'
COPY ./ecdc-web-ui/browser /usr/share/nginx/html

#### don't know what this is, but seems cool and techy
###CMD ["nginx", "-g", "daemon off;"]
CMD ["nginx", "-g", "daemon off;"]
